
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playermgt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  player-mgt-service:
    image: tostos/player-mgt:latest
    container_name: player-mgt-service-container
    depends_on:
      - postgres
    ports:
      - "8135:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/playerdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  pgdata:
